tunnel: b75039b1-7b54-4da0-b2ab-0a338bfccdc5
credentials-file: C:\Users\PC\.cloudflared\b75039b1-7b54-4da0-b2ab-0a338bfccdc5.json

ingress:
  - hostname: dvta.ch
    service: http://127.0.0.1:8000
  - hostname: www.dvta.ch
    service: http://127.0.0.1:8000
  - service: http_status:404
